# fly.toml app configuration file generated for wild-butterfly-8795 on 2023-09-16T17:25:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-butterfly-8795"
primary_region = "mad"

[build]

[dev]
PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
